// <auto-generated />
namespace LGS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_FacebookLeads_FacebookLeadDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_FacebookLeads_FacebookLeadDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201912110121105_Added_FacebookLeads_FacebookLeadDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
