// <auto-generated />
namespace LGS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_DateTimeToFacebookLeads_AddedGoogleAdKeyTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_DateTimeToFacebookLeads_AddedGoogleAdKeyTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201912121736050_Added_DateTimeToFacebookLeads_AddedGoogleAdKeyTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
