// <auto-generated />
namespace LGS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class User_Status_Removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Status_Removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201908251139580_User_Status_Removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
