// <auto-generated />
namespace LGS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class profilepicture_property_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(profilepicture_property_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201907281904498_profilepicture_property_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
