// <auto-generated />
namespace LGS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Company_Addresses_PostalCode_PhoneNumber_Email_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_Addresses_PostalCode_PhoneNumber_Email_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201908171941141_Company_Addresses_PostalCode_PhoneNumber_Email_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
