// <auto-generated />
namespace LGS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Added_CreatedDate_UpdatedDate_In_CustomerMessage_CustomerReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_CreatedDate_UpdatedDate_In_CustomerMessage_CustomerReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201911302230287_Added_CreatedDate_UpdatedDate_In_CustomerMessage_CustomerReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
